[app]
GOOGLE_API_KEY = "AQ.Ab8RN6K-XVqpoBokH9MtIu91AH680RAxrPZ8ycIsou7ID1T8HA"
COHERE_API_KEY = "cA8OzBs6mLPSUg2B5f8aPIh2jercyOe4ODBzEddT"
MONGODB_URI = "mongodb+srv://claudiobances03_db_user:usil@cluster-cfbz.kx5yksd.mongodb.net/"
USER = "Claudio Bances Zapata"
